version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_PATH: ${DATA_PATH:-data/update_category.csv}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pet_care}
      POSTGRES_USER: ${POSTGRES_USER:-wufy1234}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wufy1234}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      TZ: ${TZ:-Asia/Taipei}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pet_care}
      POSTGRES_USER: ${POSTGRES_USER:-wufy1234}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wufy1234}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
