version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_PATH: ${DATA_PATH:-data/update_category.csv}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-pet_care}
      POSTGRES_USER: ${POSTGRES_USER:-wufy1234}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wufy1234}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      TZ: ${TZ:-Asia/Taipei}
    ports:
      - "${APP_PORT:-5000}:5000"
    depends_on:
      - postgres
    command: ["sh", "-c", "./wait-for-postgres.sh postgres && python db_init.py && gunicorn --bind 0.0.0.0:5000 app:app"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pet_care}
      POSTGRES_USER: ${POSTGRES_USER:-wufy1234}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wufy1234}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_USERS_AUTO_ASSIGN_ORG=true
      - GF_USERS_AUTO_ASSIGN_ORG_ROLE=Viewer
      - GF_SECURITY_SECRET_KEY=${GRAFANA_SECRET_KEY:-your_secret_key_here}
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
